api/urls.py
from django.conf.urls import patterns, include, url

from api import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),

	url(r'^notifycount/$', views.notifyCount, name='notify-count'),

	url(r'^users/token/?$', 
		views.obtain_expiring_auth_token, 
		name='user-token'),

	# User
	url(r'^user/$', 
		views.UserList.as_view(), 
		name='user-list'),
	
	url(r'^user/(?P<pk>[0-9]+)/$', 
		views.UserDetail.as_view(), 
		name='user-detail'),

	url(r'^userextends/$', 
		views.UserExtendsList.as_view(), 
		name='user-extends-list'),
	
	url(r'^userextends/(?P<user>[0-9]+)/$', 
		views.UserExtendsDetail.as_view(), 
		name='user-extends-detail'),

	url(r'^userpicture/$', 
		views.UserPictureList.as_view(), 
		name='user-picture-list'),
	
	url(r'^userpicture/(?P<user>[0-9]+)/$', 
		views.UserPictureDetail.as_view(), 
		name='user-picture-detail'),

	url(r'^usercredit/$', 
		views.UserCreditList.as_view(), 
		name='user-credit-list'),
	
	url(r'^usercredit/(?P<user>[0-9]+)/$', 
		views.UserCreditDetail.as_view(), 
		name='user-credit-detail'),

	url(r'^geopoint/$', 
		views.GeoPointList.as_view(), 
		name='geo-point-list'),
	
	url(r'^geopoint/(?P<pk>[0-9]+)/$', 
		views.GeoPointDetail.as_view(), 
		name='geo-point-detail'),

	## Travel System
	# Travel
	url(r'^travelinfo/$', 
		views.TravelInfoList.as_view(), 
		name='travel-info-list'),
	
	url(r'^travelinfo/(?P<pk>[0-9]+)/$', 
		views.TravelInfoDetail.as_view(), 
		name='travel-info-detail'),

	url(r'^travellocal/$', 
		views.TravelLocalList.as_view(), 
		name='travel-local-list'),
	
	url(r'^travellocal/(?P<pk>[0-9]+)/$', 
		views.TravelLocalDetail.as_view(), 
		name='travel-local-detail'),

	url(r'^travelquestion/$', 
		views.TravelQuestionList.as_view(), 
		name='travel-question-list'),
	
	url(r'^travelquestion/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionDetail.as_view(), 
		name='travel-question-detail'),

	# Response
	url(r'^travelinforesponse/$', 
		views.TravelInfoResponseList.as_view(), 
		name='travel-info-response-list'),
	
	url(r'^travelinforesponse/(?P<pk>[0-9]+)/$', 
		views.TravelInfoResponseDetail.as_view(), 
		name='travel-info-response-detail'),

	url(r'^travellocalresponse/$', 
		views.TravelLocalResponseList.as_view(), 
		name='travel-local-response-list'),
	
	url(r'^travellocalresponse/(?P<pk>[0-9]+)/$', 
		views.TravelLocalResponseDetail.as_view(), 
		name='travel-local-response-detail'),

	url(r'^travelquestionresponse/$', 
		views.TravelQuestionResponseList.as_view(), 
		name='travel-question-response-list'),
	
	url(r'^travelquestionresponse/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionResponseDetail.as_view(), 
		name='travel-question-response-detail'),

	# Response Response
	url(r'^travelquestionresponseresponse/$', 
		views.TravelQuestionResponseResponseList.as_view(), 
		name='travel-question-response-response-list'),
	
	url(r'^travelquestionresponseresponse/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionResponseResponseDetail.as_view(), 
		name='travel-question-response-response-detail'),

	# Room & Message
	url(r'^room/$', 
		views.RoomList.as_view(), 
		name='room-list'),
	
	url(r'^room/(?P<pk>[0-9]+)/$', 
		views.RoomDetail.as_view(), 
		name='room-detail'),

	url(r'^message/$', 
		views.MessageList.as_view(), 
		name='message-list'),
	
	url(r'^message/(?P<pk>[0-9]+)/$', 
		views.MessageDetail.as_view(), 
		name='message-detail'),

	# Sex and the City
	url(r'^hopecity/$', 
		views.HopeCityList.as_view(), 
		name='hopecity-list'),
	
	url(r'^hopecity/(?P<pk>[0-9]+)/$', 
		views.HopeCityDetail.as_view(), 
		name='hopecity-detail'),
)

travelWithU/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from travelWithU import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	
	url(r'^intro/$', views.IntroView.as_view(), name="intro"),
	url(r'^invite/$', views.invite_send, name="invite"),
	url(r'^', include('travel_agency.urls', namespace="home")),
	url(r'^user/', include('travel_usercard.urls', namespace="user")),
	url(r'^messages/', include('travel_messenger.urls', namespace="message")),
	url(r'^travel-api/', include('api.urls', namespace="api")),
	url(r'^ckeditor/', include('ckeditor.urls')),
	# url(r'^messages/', include('postman.urls')),
	# url(r'^chat/', include('chatroom.urls')),
	url(r'^account/login/$', views.LoginView.as_view(), name="account_login"),
	url(r'^account/signup/$', views.SignupView.as_view(), name="account_signup"),
	# url(r'^account/languages/$', views.SettingsView.as_view(), name="account_settings"),
	url(r"^account/", include("account.urls")),
	url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.MEDIA_ROOT,
		}),
	)

travel_usercard/urls.py
from django.conf.urls import patterns, include, url

from travel_usercard import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^$', views.Home.as_view(), name="home"),
	# url(r'^traveler/$', views.Home.as_view(), name="home"),
)

api/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django_countries.fields import CountryField
from django.db import models
from django.dispatch import receiver

from ckeditor.fields import RichTextField
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField


def content_file_name(instance, filename):
	ext = filename.split(".")[-1]
	return 'user_pic/' + str(instance.user.username) + '.' + ext

## Relation Models
# User
# note: User has traveler and guider, 
# the difference is only at the different action can show.
# 
# - familiar country
# - familiar language
# - familiar geopoint

# Friends
# Messaging
# - Who
# - Group
# - Records

class Language(models.Model):
	name = models.CharField(max_length=254)
	country = CountryField(blank=True)

	def __unicode__(self):
		return "%s/"%self.name + "%s"%self.country


class LanguageLevel(models.Model):
	choice_levels = (
		('A', 'Great'),
		('B', 'Good'),
		('C', 'Soso'),
		('D', 'Bad'),
		('E', 'Terrible')
	)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	language = models.ForeignKey(Language)
	level = models.CharField(max_length=1, choices=choice_levels)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


class Career(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=254)
	detail = models.TextField(blank=True)
	is_current = models.BooleanField(default=True)
	start_at = models.DateTimeField(blank=True)
	end_at = models.DateTimeField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


class Education(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	school = models.CharField(max_length=254)
	department = models.CharField(max_length=254)
	degree = models.CharField(max_length=254)
	is_current = models.BooleanField(default=True)
	start_at = models.DateTimeField(blank=True)
	end_at = models.DateTimeField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


class GoodAt(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=254)
	detail = models.TextField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


class Interest(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=254)
	detail = models.TextField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


## Single Model
# User Extends, finish then start using our service
class UserExtends(models.Model):
	SEX = (
		('M', 'Male'),
		('F', 'Female'),
		('T', 'Third'),
	)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	sex = models.CharField(max_length=1, choices=SEX)
	birthday = models.DateField(blank=True)
	phone = models.CharField(max_length=254, blank=True)
	selfProfile = models.TextField(blank=True)
	country = CountryField(blank=True)
	live_country = CountryField(blank=True)
	contact_info = models.CharField(max_length=254, blank=True)
	available_time = models.CharField(max_length=254, blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

# Picture, The user picture stand alone for upload and update
class UserPicture(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	picture = models.ImageField(upload_to=content_file_name, default='/media/user_pic/default.png', null=True, blank=True)
	thumbnail = ImageRatioField('picture', '150x150')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def get_thumbnail_url(self, h, w):
		thumbnail_url = get_thumbnailer(self.picture).get_thumbnail({
			'size': (h, w),
			'box': self.thumbnail,
			'crop': True,
			'detail': True,
		}).url
		return thumbnail_url

# User's credit
class UserCredit(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	traveler_credit = models.IntegerField(default=0)
	guider_credit = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


# class UserSession(models.Model):
# 	user = models.ForeignKey(settings.AUTH_USER_MODEL)
# 	session = models.ForeignKey(Session)  


# Record who gives the credit


# Location, the point on the map
class GeoPoint(models.Model):
	longitude = models.DecimalField(max_digits=35, decimal_places=28)
	latitude = models.DecimalField(max_digits=35, decimal_places=28)
	name = models.CharField(max_length=254)
	describe = RichTextField(blank=True)
	open_time_start = models.DateTimeField(blank=True)
	open_time_end = models.DateTimeField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


class CountryCity(models.Model):
	country_name = models.CharField(max_length=254)
	country_code = models.IntegerField()
	city_name = models.CharField(max_length=254)
	city_alias = models.CharField(max_length=3)
	city_code = models.IntegerField()
	cover_photo = models.ImageField(upload_to='countries')

	def __str__(self):
		return u"%s/"%self.country_name + u"%s"%self.city_name

	class Meta:
		unique_together = ('country_code', 'city_alias',)


class ScheduleItem(models.Model):
	time = models.TimeField()
	detail = models.TextField()
	color = models.CharField(max_length=8)


class Schedule(models.Model):
	schedule_item = models.ManyToManyField(ScheduleItem)
	date = models.DateField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


## Travel System 
# TravelLocal (for Local)
class TravelLocal(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=254)
	geo_point = models.ForeignKey(GeoPoint, null=True, blank=True)
	available_time = models.CharField(max_length=254, blank=True)
	country_city = models.ForeignKey(CountryCity)
	schedule = models.ManyToManyField(Schedule, blank=True)
	detail = RichTextField(blank=True)
	notice = models.TextField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


# TravelInfo (for traveler), for the user who want to ask for advice for their travel info
class TravelInfo(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	time_start = models.DateTimeField(blank=True)
	time_end = models.DateTimeField(blank=True)
	geo_point = models.ForeignKey(GeoPoint, null=True, blank=True)
	country_city = models.ForeignKey(CountryCity)
	detail = models.TextField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

# Q&A
class TravelQuestion(models.Model):
	CATE = (
		('F', 'Food'),
		('D', 'Dress'),
		('L', 'Live'),
		('T', 'Traffic'),
		('E', 'Entertainment'),
		('EL', 'Else'),
	)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	geo_point = models.ForeignKey(GeoPoint, null=True, blank=True)
	country_city = models.ForeignKey(CountryCity)
	rate = models.IntegerField(default=0)
	views = models.IntegerField(default=0)
	title = models.CharField(max_length=254)
	detail = RichTextField(blank=True)
	categories = models.CharField(max_length=2, choices=CATE)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

# Travel Local's response (for user)
class TravelLocalResponse(models.Model):
	travel_local = models.ForeignKey(TravelLocal, on_delete=models.CASCADE)
	user = models.ForeignKey(User)
	suggestion = RichTextField(config_name='response', blank=True)
	is_connection = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	# [REF] it throws a django.db.utils.IntegrityError if you try to add a duplicate
	class Meta:
		unique_together = ('travel_local', 'user',)


# Travel Info's response (for guider)
class TravelInfoResponse(models.Model):
	travel_info = models.ForeignKey(TravelInfo, on_delete=models.CASCADE)
	user = models.ForeignKey(User)
	suggestion = RichTextField(config_name='response', blank=True)
	is_connection = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	# [REF] it throws a django.db.utils.IntegrityError if you try to add a duplicate
	class Meta:
		unique_together = ('travel_info', 'user',)

# Travel Question's response (any)
class TravelQuestionResponse(models.Model):
	travel_question = models.ForeignKey(TravelQuestion, on_delete=models.CASCADE)
	user = models.ForeignKey(User)
	detail = RichTextField(blank=True)
	rate = models.IntegerField(default=0)
	is_connection = models.BooleanField(default=True)
	is_choose = models.BooleanField(default=False)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		unique_together = ('travel_question', 'user',)

# Travel Question response's response (any)
class TravelQuestionResponseResponse(models.Model):
	travel_question_response = models.ForeignKey(TravelQuestionResponse, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	detail = RichTextField(config_name='response', blank=True)
	rate = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


# Sex and the City XDDDDD shit >//<
class HopeCity(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	country = models.CharField(max_length=254)
	city = models.CharField(max_length=254, blank=True)

travel_usercard/models.py
from django.db import models

# Create your models here.

travel_usercard/views.py
from django.views import generic
from django.shortcuts import redirect

from api.models import UserExtends, UserPicture, LanguageLevel, TravelLocal, Education, Career, Interest, GoodAt

# Create your views here.
class Home(generic.TemplateView):
	template_name = 'travel_usercard/home.html'

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		else:
			return super(Home, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(Home, self).get_context_data(**kwargs)
		user = self.request.user

		context['current'] = {'title' : 'None'}
		try:
			context['user_extends'] = UserExtends.objects.get(user=user)
		except UserExtends.DoesNotExist:
			pass

		try:
			context['user_picture'] = UserPicture.objects.get(user=user)
		except UserPicture.DoesNotExist:
			pass

		try:
			context['current'] = Career.objects.get(user=user, is_current=True)
		except Career.DoesNotExist:
			try:
				context['current'] = {'title' : 'Student'}
				context['education'] = Education.objects.get(user=user, is_current=True)
			except Education.DoesNotExist:
				try:
					context['education'] = Education.objects.filter(user=user).latest('end_at')
				except Education.DoesNotExist:
					pass

		# context['educations'] = Education.objects.filter(user=user)
		# context['careers'] = Career.objects.filter(user=user)
		context['interests'] = Interest.objects.filter(user=user)
		context['goodats'] = GoodAt.objects.filter(user=user)
		context['language_levels'] = LanguageLevel.objects.filter(user=user)
		context['travel_locals'] = TravelLocal.objects.filter(user=user)
		return context

templates/travel_usercard/home.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}
{% load staticfiles %}

{% block head_title %}{% trans "Traveler" %}{% endblock %}

<!--
load socketio_tags
socketio
-->

{% block fullpage_css %}
	<!-- Full Page -->
	<link rel="stylesheet" href="{% static "css/fullPage/jquery.fullPage.css" %}" />
{% endblock %}

{% block css_extends %}
<style type="text/css">

/* padding top for fixed navbar */
.section { 
	/* Original section has border box in jquery.fullPage.css */
	padding-top: 54px;
}

h3 {
	text-align: center;
}

.local-menu-group {
	position: fixed;
	top: 54px;
	right: 5em;
	z-index: 1;
}

.card-loacl-handle {
}

.card-local-menu {
	overflow: auto;
}

.card-local-menu-item {

}

.user-detail {
	padding-bottom: 54px;
}

.user-detail-about {
	position: absolute;
	left: 0;
	right: 0;
	bottom: 40px;
}

.data-frame {
	border-style: solid;
	border-width: 5px;
	border-color: red;
	/* Haha margin is really shit with bootstrap.. */
}
</style>
{% endblock %}

{% block nav_fix %}navbar-fixed-top{% endblock %}

{% block body %}
<div id="fullpage">
	<div class="user-card section">
		<div class="row">
			<div class="col-md-3">
				{% if user_picture %}
					<img class="img-circle img-responsive" src="{{ user_picture.picture.url }}">
				{% endif %}
			</div>
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-4">
						<div class="row">{% trans "Name" %}</div>
						<div class="row">{% trans "Country" %}</div>
						<div class="row">{% trans "Language" %}</div>
					</div>
					<div class="col-md-8">
						<div class="row">{{ user.first_name }}</div>
						<div class="row">
							{% if user_extends %}
								{{ user_extends.country.name }}
							{% endif %}
						</div>
						<div class="row"></div>
					</div>
				</div>
			</div>
			<div class="col-md-3">
			</div>
		</div>
		
		<a id="about_handle" href="#" class="user-detail-about">
			<h3>{% trans "About Me" %}</h3>
		</a>
	</div>

	<div class="user-detail section">
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<h3>{{ user.first_name }}</h3>
			</div>
			<div class="col-md-4"></div>
		</div>
		<div class="row">
			{% if user_extends %}
			<!-- Basic data -->
			<div class="col-md-6 data-frame">
				<!-- Gender -->
				<div class="row">
					<div class="col-md-2">
						<img class="img-responsive" src="{% static "icon/gender.png" %}">
					</div>
					<div class="col-md-10">
						{{ user_extends.get_sex_display }}
					</div>
				</div>

				<!-- Country -->
				<div class="row">
					<div class="col-md-2">
						<img class="img-responsive" src="{% static "icon/location.png" %}">
					</div>
					<div class="col-md-10">
						<div class="row">
							<div class="col-md-2">
								<img class="img-responsive" src="{{ user_extends.country.flag }}">
							</div>
							<div class="col-md-10">
								{{ user_extends.country.name }}
							</div>
						</div>
					</div>
				</div>

				<!-- Bitrhday -->
				<div class="row">
					<div class="col-md-2">
						<img class="img-responsive" src="{% static "icon/birth.png" %}">
					</div>
					<div class="col-md-10">
						{{ user_extends.birthday|date:"Y/m/d" }}
					</div>
				</div>

				{% if education %}
				<!-- Education -->
				<div class="row">
					<div class="col-md-2">
						<img class="img-responsive" src="{% static "icon/education.png" %}">
					</div>
					<div class="col-md-10">
						{{ education.degree }}, {{ education.department }}, 
						{% if education.end_at %}
							{{ education.end_at|date:"Y" }}, 
						{% endif %}
						{{ education.school }}
					</div>
				</div>
				{% endif %}

				{% if current %}
				<!-- Current -->
				<div class="row">
					<div class="col-md-2">
						<img class="img-responsive" src="{% static "icon/jobs.png" %}">
					</div>
					<div class="col-md-10">
						{{ current.title }}
					</div>
				</div>
				{% endif %}

				{% if goodats %}
				<!-- GoodAt -->
				<div class="row">
					<div class="col-md-2">
						<img class="img-responsive" src="{% static "icon/skill.png" %}">
					</div>
					<div class="col-md-10">
						{% for goodat in goodats %}
							{{ goodat.name }}
						{% endfor %}
					</div>
				</div>
				{% endif %}

				{% if interests %}
				<!-- Interest -->
				<div class="row">
					<div class="col-md-2">
						<img class="img-responsive" src="{% static "icon/interest.png" %}">
					</div>
					<div class="col-md-10">
						{% for interest in interests %}
							{{ interest.name }}
						{% endfor %}
					</div>
				</div>
				{% endif %}
			</div>

			<!-- Personal Detail -->
			<div class="col-md-6 data-frame">
				{{ user_extends.selfProfile|safe }}
			</div>
			{% endif %}
		</div>
	</div>
</div>

<div class="local-menu-group">
	<div class="row">
		<a id="local_handle" class="card-loacl-handle navbar-brand toggle-button">
			<h1>{% trans "Local Post" %}</h1>
		</a>
	</div>
	<div class="row">
		<div id="local_menu" class="card-local-menu list-group">
			{% for travel_local in travel_locals %}
			<div class="card-local-menu-item list-group-item">
				<h3>{{ travel_local.title }}</h3>
				<div class="row">
					<div class="col-md-offset-1 col-md-11">
						<div class="row">{{ travel_local.country_city }}</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

{% block fullpage_js %}
	<!-- Full Page JS -->
	<!-- This following line is needed only in case of using other easing effect rather than "linear", "swing" or "easeInQuart". You can also add the full jQuery UI instead of this file if you prefer -->
	<script src="{% static "js/fullPage/vendors/jquery.easings.min.js" %}"></script>
	<!-- This following line needed in the case of using the plugin option `scrollOverflow:true` -->
	<script type="text/javascript" src="{% static "js/fullPage/vendors/jquery.slimscroll.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/fullPage/jquery.fullPage.js" %}"></script>
	<script type="text/javascript" src="{% static "js/fullPage/user_card.conf.js" %}"></script>
{% endblock %}

{% block end_js_extends %}
<!-- <script src="{% static "js/nav_local.js" %}"></script> -->
{% endblock %}