api/urls.py
from django.conf.urls import patterns, include, url

from api import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),

	url(r'^notifycount/$', views.notifyCount, name='notify-count'),

	url(r'^users/token/?$', 
		views.obtain_expiring_auth_token, 
		name='user-token'),

	# User
	url(r'^user/$', 
		views.UserList.as_view(), 
		name='user-list'),
	
	url(r'^user/(?P<pk>[0-9]+)/$', 
		views.UserDetail.as_view(), 
		name='user-detail'),

	url(r'^userextends/$', 
		views.UserExtendsList.as_view(), 
		name='user-extends-list'),
	
	url(r'^userextends/(?P<user>[0-9]+)/$', 
		views.UserExtendsDetail.as_view(), 
		name='user-extends-detail'),

	url(r'^userpicture/$', 
		views.UserPictureList.as_view(), 
		name='user-picture-list'),
	
	url(r'^userpicture/(?P<user>[0-9]+)/$', 
		views.UserPictureDetail.as_view(), 
		name='user-picture-detail'),

	url(r'^usercredit/$', 
		views.UserCreditList.as_view(), 
		name='user-credit-list'),
	
	url(r'^usercredit/(?P<user>[0-9]+)/$', 
		views.UserCreditDetail.as_view(), 
		name='user-credit-detail'),

	url(r'^geopoint/$', 
		views.GeoPointList.as_view(), 
		name='geo-point-list'),
	
	url(r'^geopoint/(?P<pk>[0-9]+)/$', 
		views.GeoPointDetail.as_view(), 
		name='geo-point-detail'),

	## Travel System
	# Travel
	url(r'^travelinfo/$', 
		views.TravelInfoList.as_view(), 
		name='travel-info-list'),
	
	url(r'^travelinfo/(?P<pk>[0-9]+)/$', 
		views.TravelInfoDetail.as_view(), 
		name='travel-info-detail'),

	url(r'^travellocal/$', 
		views.TravelLocalList.as_view(), 
		name='travel-local-list'),
	
	url(r'^travellocal/(?P<pk>[0-9]+)/$', 
		views.TravelLocalDetail.as_view(), 
		name='travel-local-detail'),

	url(r'^travelquestion/$', 
		views.TravelQuestionList.as_view(), 
		name='travel-question-list'),
	
	url(r'^travelquestion/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionDetail.as_view(), 
		name='travel-question-detail'),

	# Response
	url(r'^travelinforesponse/$', 
		views.TravelInfoResponseList.as_view(), 
		name='travel-info-response-list'),
	
	url(r'^travelinforesponse/(?P<pk>[0-9]+)/$', 
		views.TravelInfoResponseDetail.as_view(), 
		name='travel-info-response-detail'),

	url(r'^travellocalresponse/$', 
		views.TravelLocalResponseList.as_view(), 
		name='travel-local-response-list'),
	
	url(r'^travellocalresponse/(?P<pk>[0-9]+)/$', 
		views.TravelLocalResponseDetail.as_view(), 
		name='travel-local-response-detail'),

	url(r'^travelquestionresponse/$', 
		views.TravelQuestionResponseList.as_view(), 
		name='travel-question-response-list'),
	
	url(r'^travelquestionresponse/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionResponseDetail.as_view(), 
		name='travel-question-response-detail'),

	# Response Response
	url(r'^travelquestionresponseresponse/$', 
		views.TravelQuestionResponseResponseList.as_view(), 
		name='travel-question-response-response-list'),
	
	url(r'^travelquestionresponseresponse/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionResponseResponseDetail.as_view(), 
		name='travel-question-response-response-detail'),

	# Room & Message
	url(r'^room/$', 
		views.RoomList.as_view(), 
		name='room-list'),
	
	url(r'^room/(?P<pk>[0-9]+)/$', 
		views.RoomDetail.as_view(), 
		name='room-detail'),

	url(r'^message/$', 
		views.MessageList.as_view(), 
		name='message-list'),
	
	url(r'^message/(?P<pk>[0-9]+)/$', 
		views.MessageDetail.as_view(), 
		name='message-detail'),

	# Sex and the City
	url(r'^hopecity/$', 
		views.HopeCityList.as_view(), 
		name='hopecity-list'),
	
	url(r'^hopecity/(?P<pk>[0-9]+)/$', 
		views.HopeCityDetail.as_view(), 
		name='hopecity-detail'),
)

travelWithU/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from travelWithU import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	
	url(r'^intro/$', views.IntroView.as_view(), name="intro"),
	url(r'^invite/$', views.invite_send, name="invite"),
	url(r'^', include('travel_agency.urls', namespace="home")),
	url(r'^user/', include('travel_usercard.urls', namespace="user")),
	url(r'^messages/', include('travel_messenger.urls', namespace="message")),
	url(r'^travel-api/', include('api.urls', namespace="api")),
	url(r'^ckeditor/', include('ckeditor.urls')),
	# url(r'^messages/', include('postman.urls')),
	# url(r'^chat/', include('chatroom.urls')),
	url(r'^account/login/$', views.LoginView.as_view(), name="account_login"),
	url(r'^account/signup/$', views.SignupView.as_view(), name="account_signup"),
	# url(r'^account/languages/$', views.SettingsView.as_view(), name="account_settings"),
	url(r"^account/", include("account.urls")),
	url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.MEDIA_ROOT,
		}),
	)

travel_agency/urls.py
from django.conf.urls import patterns, include, url

from travel_agency import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^$', views.Chooser.as_view(), name="chooser"),
	url(r'^traveler/$', views.Home.as_view(), name="home"),
	# url(r'', include('user_sessions.urls', 'user_sessions')),
	# url(r'', include('django_socketio.urls')),
	# url(r'^node_api/$', views.node_api, name='node_api'),
	# url(r'^chat/$', include('chatrooms.urls')),
	url(r'^settings/$', views.ExtendsView.as_view(), name="extends"),
	url(r'^profile-pic/$', views.ProfilePicView.as_view(), name="pic"),
	url(r'^traveler/main-travel-info/$', views.MainTravelInfoView.as_view(), name="main-travel-info"),
	url(r'^traveler/main-travel-local/$', views.MainTravelLocalView.as_view(), name="main-travel-local"),
	url(r'^traveler/main-travel-question/$', views.MainTravelQuestionView.as_view(), name="main-travel-question"),
	url(r'^traveler/travel-local/$', views.TravelLocalView.as_view(), name="travel-local-form"),
	url(r'^traveler/travel-info/$', views.TravelInfoView.as_view(), name="travel-info-form"),
	url(r'^traveler/travel-question/(?P<pk>[0-9]+)/$', views.TravelQuestionUpdateView.as_view(), name="travel-question-update-form"),
	url(r'^traveler/travel-local/(?P<pk>[0-9]+)/$', views.TravelLocalUpdateView.as_view(), name="travel-local-update-form"),
	url(r'^traveler/travel-info/(?P<pk>[0-9]+)/$', views.TravelInfoUpdateView.as_view(), name="travel-info-update-form"),
	url(r'^traveler/travel-question/$', views.TravelQuestionView.as_view(), name="travel-question-form"),
	url(r'^traveler/travel-info-response/$', views.TravelInfoResponseView.as_view(), name="travel-info-res-form"),
	url(r'^traveler/travel-question-response/$', views.TravelQuestionResponseView.as_view(), name="travel-question-res-form"),
	url(r'^traveler/travel-question-res-res/$', views.TravelQuestionResponseResponseView.as_view(), name="travel-question-res-res-form"),
)

travel_messenger/urls.py
from django.conf.urls import patterns, include, url

from travel_messenger import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^$', views.Index.as_view(), name="index"),
	url(r'^req_msg/$', views.request_to_msg, name="req_to_msg"),
	url(r'^node_api/$', views.node_api, name='node_api'),
)

templates/_account_bar.html
{% load i18n %}
{% load account_tags %}
{% load url from future %}

<ul class="nav navbar-nav navbar-right">
    {% if request.user.is_authenticated %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {% user_display request.user %}
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url "account_settings" %}"><i class="fa fa-user"></i> {% trans "Settings" %}</a></li>
                {% if request.user.is_staff %}
                    <li><a href="{% url THEME_ADMIN_URL|default:"admin:index" %}"><i class="fa fa-cog"></i> {% trans "Admin" %}</a></li>
                {% endif %}
                <li class="divider"></li>
                <li>
                    <a id="account_logout" href="{% url "account_logout" %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
                </li>
            </ul>
        </li>
    {% else %}
        <li><a class="btn btn-success navbar-btn" href="{% url "account_login" %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a class="btn btn-primary navbar-btn" href="{% url "account_signup" %}">{% trans "Sign up" %}</a></li>
            <!-- <li><a href="{% url "account_login" %}">{% trans "Log in" %}</a></li> -->
            <!-- <li><a href="{% url "account_signup" %}">{% trans "Sign up" %}</a></li> -->
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url "account_logout" %}" method="POST">
    {% csrf_token %}
</form>

templates/_invite_user.html
{% load i18n %}
{% load bootstrap %}
{% load staticfiles %}

<!-- Modal -->
<div class="modal fade" id="invite_user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<div class="row">
					<div class="col-md-4"></div>
					<div class="col-md-4">
						<h4 class="modal-title" id="myModalLabel">{% trans "Invite Friends!" %}</h4>
					</div>
					<div class="col-md-4"></div>
				</div>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-2"></div>
					<div class="col-md-8">
						{% trans "Friends Email" %}
						<input id="email" class="form-control" type="text" placeholder="Email...">
					</div>
					<div class="col-md-2"></div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="form-control btn btn-primary" data-dismiss="modal" onClick="inviteFriends()">Send</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

function inviteFriends() {
	var email = $('#email').val();
	console.log(email);
	$.ajax( {
		url: "{% url 'invite' %}",
		type: 'POST',
		data: {
			email: email
		},
		success: function(data) {
			console.log(data);
		}
	});
}
</script>

templates/_io_script.html
{% load staticfiles %}

<script src="{% static 'js/chatroom/jquery_csrf_ajax.js' %}"></script>
<script src="http://inlocal.tw/socket.io/socket.io.js"></script>

templates/_messages.html
{% for message in messages %}
    <div class="alert fade in">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}

templates/site_base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html class="no-js" lang="{{ LANGUAGE_CODE }}">
<head>

	<meta charset="utf-8">
	<!-- If you delete this meta tag World War Z will become a reality -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>{% block head_title %}{% endblock %} | TravelWithU</title>
	<link rel="shortcut icon" href="{% static "favicon.ico" %}" />
	<!-- <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/smoothness/jquery-ui.css" /> -->

	<!-- Bootstrap -->
	<link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.css" %}">
	<link rel="stylesheet" href="{% static "css/bootstrap/bootstrap-theme.css" %}">

	<!-- jQuery -->
	<script src="{% static "jquery/js/jquery-2.1.4.js" %}"></script>
	<script src="{% static "jquery/js/jquery-ui-1.11.4/jquery-ui.js" %}"></script>
	<script src="{% static "js/angularjs/angular.js" %}"></script>
	<script src="{% static "js/load_images.js" %}"></script> 

	{% block fullpage_css %}
	{% endblock %}

	<link rel="stylesheet" href="{% static "css/intro.css" %}" />
	<link rel="stylesheet" href="{% static "css/travel.css" %}" />
	<link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.css" %}">
	<!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"> -->

	{% block css_extends %}
	{% endblock %}


	{% block notify %}
		{% if user.is_authenticated %}
			<script type="text/javascript">
			$(document).ready(function() {
				var socket = io.connect('inlocal.tw', { autoConnect: true});

				// TODO get the new message notify
				socket.on('connect', function() {
					console.log("notify connect?");
					socket.emit('notify', {{ user.pk }}, function(data) {
						console.log(data);
					});
				});

				socket.on('notifier', function(msg) {
					console.log(msg);
					getNotifyNumber();
				});
			});
			</script>
		{% endif %}
	{% endblock %}
	{% block extra_head %}{% endblock %}
</head>

<body {% if user.is_authenticated %}onload="getNavUserInformation({{ user.pk }});"{% endif %}>
	<div id="navbar" class="navbar {% block nav_fix %}navbar-static-top{% endblock %}">
		<div class="container-fluid container-navbar">
		{% block topbar %}
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url "home:chooser" %}">
					<img class="navbar-brand-default" src="{% static "travelwithu/inLocal_logo.png" %}"></a>
			</div>

			<div class="collapse navbar-collapse navbar-right" style="margin-top: 0.33em">
				{% if user.is_authenticated %}
				<div class="row nav navbar-nav">
					<!-- <a class="col-md-4 navbar-brand" id="#profile_name" href="{% url "user:home" %}"></a>
					<a class="col-md-3" href="{% url "user:home" %}">
						<img id="#profile_pic" class="img-rounded" style="height:48px" src="/media/user_pic/default.png">
					</a>
					<a class="col-md-2" href="{% url "message:index" %}">
						<img style="height:48px" src="{% static "travelwithu/alert.png" %}">
					</a>
					<div class="col-md-1">
						<span data-type="notify" data-url="{% url 'api:notify-count' %}" class="badge"></span>
					</div> -->
					<div class="pull-right">
						<div class="dropdown">
							<a href="#" class="dropdown-toggle btn-link" data-toggle="dropdown">
								<img data-user-img="{{ user.pk }}" class="nav-icon-default" src="{% static "travelwithu/nav_setting.png" %}"></img>
							</a>
							<ul class="dropdown-menu">
								<li><a href="{% url "home:extends" %}"><i class="fa fa-user"></i> {% trans "Settings" %}</a></li>
								<li><a href="{% url "account_settings" %}"><i class="fa fa-language"></i> {% trans "Languages" %}</a></li>
								<!-- <li><a href="" data-toggle="modal" data-target="#invite_user"><i class="fa fa-share-alt"></i> {% trans "Invite Friends" %}</a></li> -->
								{% if user.is_staff %}
									<li><a href="{% url THEME_ADMIN_URL|default:"admin:index" %}"><i class="fa fa-cog"></i> {% trans "Admin" %}</a></li>
								{% endif %}
								<li class="divider"></li>
								<li>
									<a id="account_logout" href="{% url "account_logout" %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="pull-right">
						<span data-type="notify" data-url="{% url 'api:notify-count' %}" class="badge"></span>
					</div>
					<div class="pull-right">
						<a href="{% url "message:index" %}">
							<img class="nav-icon-default" src="{% static "travelwithu/nav_notify.png" %}">
						</a>
					</div>
					<div class="pull-right">
						<a href="{% url "user:home" %}">
							<img id="#profile_pic" class="img-rounded nav-icon-default" src="{% static "travelwithu/nav_user_2.png" %}">
						</a>
						<a id="#profile_name" href="{% url "user:home" %}"></a>
					</div>
				</div>
				{% else %}
					{% block page-si %}
						{% if ACCOUNT_OPEN_SIGNUP %}
							<a class="navbar-btn-signup" href="{% url "account_signup" %}">Sign Up</a>
						{% endif %}
						<a class="navbar-btn-login" href="{% url "account_login" %}">Log In</a>
					{% endblock %}
				{% endif %}
			</div>

			<form id="accountLogOutForm" style="display: none;" action="{% url "account_logout" %}" method="POST">
				{% csrf_token %}
			</form>
		{% endblock %}
		</div>
	</div>

	{% block body_base %}
		<!-- <section id="content_body"> -->
		<div class="container">
			{% include "_messages.html" %}
			<!-- 
			{ block postman }
			{ endblock }
			 -->
			{% block body %}
			{% endblock %}
		</div>
		<!-- </section> -->
	{% endblock %}

	{% block footer_base %}
		<footer>
			<div class="container">
				{% block footer %}{% endblock %}
			</div>
		</footer>
	{% endblock %}

	<!-- { include "_invite_user.html" } -->

	{% include "_io_script.html" %}

	<!-- Bootstrap -->
	<script src="{% static "js/bootstrap/bootstrap.js" %}"></script> 
	<script src="{% static "js/travel.js" %}"></script> 

	{% block fullpage_js %}
	{% endblock %}

	{% block end_js_extends %}
	{% endblock %}
</body>

</html>