api/urls.py
from django.conf.urls import patterns, include, url

from api import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),

	url(r'^notifycount/$', views.notifyCount, name='notify-count'),

	url(r'^users/token/?$', 
		views.obtain_expiring_auth_token, 
		name='user-token'),

	# User
	url(r'^user/$', 
		views.UserList.as_view(), 
		name='user-list'),
	
	url(r'^user/(?P<pk>[0-9]+)/$', 
		views.UserDetail.as_view(), 
		name='user-detail'),

	url(r'^userextends/$', 
		views.UserExtendsList.as_view(), 
		name='user-extends-list'),
	
	url(r'^userextends/(?P<user>[0-9]+)/$', 
		views.UserExtendsDetail.as_view(), 
		name='user-extends-detail'),

	url(r'^userpicture/$', 
		views.UserPictureList.as_view(), 
		name='user-picture-list'),
	
	url(r'^userpicture/(?P<user>[0-9]+)/$', 
		views.UserPictureDetail.as_view(), 
		name='user-picture-detail'),

	url(r'^usercredit/$', 
		views.UserCreditList.as_view(), 
		name='user-credit-list'),
	
	url(r'^usercredit/(?P<user>[0-9]+)/$', 
		views.UserCreditDetail.as_view(), 
		name='user-credit-detail'),

	url(r'^geopoint/$', 
		views.GeoPointList.as_view(), 
		name='geo-point-list'),
	
	url(r'^geopoint/(?P<pk>[0-9]+)/$', 
		views.GeoPointDetail.as_view(), 
		name='geo-point-detail'),

	## Travel System
	# Travel
	url(r'^travelinfo/$', 
		views.TravelInfoList.as_view(), 
		name='travel-info-list'),
	
	url(r'^travelinfo/(?P<pk>[0-9]+)/$', 
		views.TravelInfoDetail.as_view(), 
		name='travel-info-detail'),

	url(r'^travellocal/$', 
		views.TravelLocalList.as_view(), 
		name='travel-local-list'),
	
	url(r'^travellocal/(?P<pk>[0-9]+)/$', 
		views.TravelLocalDetail.as_view(), 
		name='travel-local-detail'),

	url(r'^travelquestion/$', 
		views.TravelQuestionList.as_view(), 
		name='travel-question-list'),
	
	url(r'^travelquestion/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionDetail.as_view(), 
		name='travel-question-detail'),

	# Response
	url(r'^travelinforesponse/$', 
		views.TravelInfoResponseList.as_view(), 
		name='travel-info-response-list'),
	
	url(r'^travelinforesponse/(?P<pk>[0-9]+)/$', 
		views.TravelInfoResponseDetail.as_view(), 
		name='travel-info-response-detail'),

	url(r'^travellocalresponse/$', 
		views.TravelLocalResponseList.as_view(), 
		name='travel-local-response-list'),
	
	url(r'^travellocalresponse/(?P<pk>[0-9]+)/$', 
		views.TravelLocalResponseDetail.as_view(), 
		name='travel-local-response-detail'),

	url(r'^travelquestionresponse/$', 
		views.TravelQuestionResponseList.as_view(), 
		name='travel-question-response-list'),
	
	url(r'^travelquestionresponse/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionResponseDetail.as_view(), 
		name='travel-question-response-detail'),

	# Response Response
	url(r'^travelquestionresponseresponse/$', 
		views.TravelQuestionResponseResponseList.as_view(), 
		name='travel-question-response-response-list'),
	
	url(r'^travelquestionresponseresponse/(?P<pk>[0-9]+)/$', 
		views.TravelQuestionResponseResponseDetail.as_view(), 
		name='travel-question-response-response-detail'),

	# Room & Message
	url(r'^room/$', 
		views.RoomList.as_view(), 
		name='room-list'),
	
	url(r'^room/(?P<pk>[0-9]+)/$', 
		views.RoomDetail.as_view(), 
		name='room-detail'),

	url(r'^message/$', 
		views.MessageList.as_view(), 
		name='message-list'),
	
	url(r'^message/(?P<pk>[0-9]+)/$', 
		views.MessageDetail.as_view(), 
		name='message-detail'),

	# Sex and the City
	url(r'^hopecity/$', 
		views.HopeCityList.as_view(), 
		name='hopecity-list'),
	
	url(r'^hopecity/(?P<pk>[0-9]+)/$', 
		views.HopeCityDetail.as_view(), 
		name='hopecity-detail'),
)

travelWithU/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from travelWithU import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	
	url(r'^intro/$', views.IntroView.as_view(), name="intro"),
	url(r'^invite/$', views.invite_send, name="invite"),
	url(r'^', include('travel_agency.urls', namespace="home")),
	url(r'^user/', include('travel_usercard.urls', namespace="user")),
	url(r'^messages/', include('travel_messenger.urls', namespace="message")),
	url(r'^travel-api/', include('api.urls', namespace="api")),
	url(r'^ckeditor/', include('ckeditor.urls')),
	# url(r'^messages/', include('postman.urls')),
	# url(r'^chat/', include('chatroom.urls')),
	url(r'^account/login/$', views.LoginView.as_view(), name="account_login"),
	url(r'^account/signup/$', views.SignupView.as_view(), name="account_signup"),
	# url(r'^account/languages/$', views.SettingsView.as_view(), name="account_settings"),
	url(r"^account/", include("account.urls")),
	url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.MEDIA_ROOT,
		}),
	)

travel_agency/urls.py
from django.conf.urls import patterns, include, url

from travel_agency import views

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'travelWithU.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^$', views.Chooser.as_view(), name="chooser"),
	url(r'^traveler/$', views.Home.as_view(), name="home"),
	# url(r'', include('user_sessions.urls', 'user_sessions')),
	# url(r'', include('django_socketio.urls')),
	# url(r'^node_api/$', views.node_api, name='node_api'),
	# url(r'^chat/$', include('chatrooms.urls')),
	url(r'^settings/$', views.ExtendsView.as_view(), name="extends"),
	url(r'^profile-pic/$', views.ProfilePicView.as_view(), name="pic"),
	url(r'^traveler/main-travel-info/$', views.MainTravelInfoView.as_view(), name="main-travel-info"),
	url(r'^traveler/main-travel-local/$', views.MainTravelLocalView.as_view(), name="main-travel-local"),
	url(r'^traveler/main-travel-question/$', views.MainTravelQuestionView.as_view(), name="main-travel-question"),
	url(r'^traveler/travel-local/$', views.TravelLocalView.as_view(), name="travel-local-form"),
	url(r'^traveler/travel-info/$', views.TravelInfoView.as_view(), name="travel-info-form"),
	url(r'^traveler/travel-question/(?P<pk>[0-9]+)/$', views.TravelQuestionUpdateView.as_view(), name="travel-question-update-form"),
	url(r'^traveler/travel-local/(?P<pk>[0-9]+)/$', views.TravelLocalUpdateView.as_view(), name="travel-local-update-form"),
	url(r'^traveler/travel-info/(?P<pk>[0-9]+)/$', views.TravelInfoUpdateView.as_view(), name="travel-info-update-form"),
	url(r'^traveler/travel-question/$', views.TravelQuestionView.as_view(), name="travel-question-form"),
	url(r'^traveler/travel-info-response/$', views.TravelInfoResponseView.as_view(), name="travel-info-res-form"),
	url(r'^traveler/travel-question-response/$', views.TravelQuestionResponseView.as_view(), name="travel-question-res-form"),
	url(r'^traveler/travel-question-res-res/$', views.TravelQuestionResponseResponseView.as_view(), name="travel-question-res-res-form"),
)

travel_agency/models.py
from django.db import models

# Create your models here.

travel_agency/views.py
from django.views import generic
from django.views.generic.edit import FormView, CreateView, UpdateView
# from django.views.generic.edit import UpdateView, DeleteView
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in
from django.db.models import Count
from django.shortcuts import redirect

# from account.utils import user_display

from rest_framework.decorators import api_view
# authentication_classes

# from api import models
# from api.auth import ExpiringTokenAuthentication
from api.models import UserExtends, UserPicture, CountryCity, TravelInfo, TravelQuestion, TravelInfoResponse, TravelQuestionResponse, TravelQuestionResponseResponse, TravelLocal, TravelLocalResponse

from travel_agency import forms

import warnings



# def user_logged_in_handler(sender, request, user, **kwargs):
# 	UserSession.objects.get_or_create(
# 		user = user, session_id = request.session.session_key
# 	)


# def delete_user_sessions(user):
# 	user_sessions = UserSession.objects.filter(user = user)
# 	for user_session in user_session:
# 		user_session.session.delete()


# user_logged_in.connect(user_logged_in_handler)


class Chooser(generic.TemplateView):
	template_name = 'travel_agency/chooser.html'

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		else:
			return super(Chooser, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(Chooser, self).get_context_data(**kwargs)
		context['countries'] = CountryCity.objects.all()
		return context


class Home(generic.TemplateView):
	template_name = 'travel_agency/home.html'

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		elif not request.GET.get('country', None):
			return redirect('home:chooser')
		else:
			# user_display(request.user)
			return super(Home, self).dispatch(request, *args, **kwargs)

	## Test user messaging, [remove when publish]
	def get_context_data(self, **kwargs):
		context = super(Home, self).get_context_data(**kwargs)
		# if self.request.user.is_authenticated:
		# warnings.simplefilter('error', DeprecationWarning)
		get_country_city = self.request.GET.get('country', None)
		cc = get_country_city.split("-")
		country_city = CountryCity.objects.get(country_code=int(cc[0]), city_alias=cc[1])

		travel_locals = TravelLocal.objects.filter(country_city=country_city).annotate(res_count=Count('travellocalresponse'))
		travel_infos = TravelInfo.objects.filter(country_city=country_city).annotate(res_count=Count('travelinforesponse'))
		travel_questions = TravelQuestion.objects.filter(country_city=country_city).annotate(res_count=Count('travelquestionresponse'))

		context['users'] = User.objects.all()
		context['travel_locals'] = travel_locals
		context['travel_infos'] = travel_infos
		context['travel_questions'] = travel_questions
		context['country'] = self.request.GET.get('country', None)
		return context

class MainTravelInfoView(generic.TemplateView):
	template_name = 'travel_agency/travel_infos/_main_travel_info_home.html'

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		else:
			# user_display(request.user)
			return super(MainTravelInfoView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(MainTravelInfoView, self).get_context_data(**kwargs)

		travel_info_id = self.request.GET.get('travel_info_id', None)
		travel_info = TravelInfo.objects.get(pk=travel_info_id)
		travel_info_responses = TravelInfoResponse.objects.filter(travel_info=travel_info).order_by('created_at')

		context['travel_info'] = travel_info
		context['travel_info_responses'] = travel_info_responses
		# context['travel_info_response_form'] = forms.TravelInfoResponseForm

		return context


class MainTravelLocalView(generic.TemplateView):
	template_name = 'travel_agency/travel_locals/_main_travel_local_home.html'

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		else:
			# user_display(request.user)
			return super(MainTravelLocalView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(MainTravelLocalView, self).get_context_data(**kwargs)

		travel_local_id = self.request.GET.get('travel_local_id', None)
		travel_local = TravelLocal.objects.get(pk=travel_local_id)
		travel_local_responses = TravelLocalResponse.objects.filter(travel_local=travel_local).order_by('created_at')

		context['travel_local'] = travel_local
		context['travel_local_responses'] = travel_local_responses
		# context['travel_info_response_form'] = forms.TravelInfoResponseForm

		return context


class MainTravelQuestionView(generic.TemplateView):
	template_name = 'travel_agency/travel_questions/_main_travel_question_home.html'

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		else:
			# user_display(request.user)
			return super(MainTravelQuestionView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(MainTravelQuestionView, self).get_context_data(**kwargs)

		travel_question_id = self.request.GET.get('travel_question_id', None)
		travel_question = TravelQuestion.objects.get(pk=travel_question_id)
		travel_question_responses = TravelQuestionResponse.objects.filter(travel_question=travel_question).order_by('created_at')
		travel_question_res_res_s = TravelQuestionResponseResponse.objects.filter(
			travel_question_response__in=travel_question_responses
		).order_by('created_at')

		res_res_s = {}
		for res in travel_question_responses:
			res_res_s[res.pk] = (TravelQuestionResponseResponse.objects.filter(travel_question_response=res).order_by('created_at'))

		context['travel_question'] = travel_question
		context['travel_question_responses'] = travel_question_responses
		context['travel_question_res_res_s'] = res_res_s
		# context['travel_question_response_form'] = forms.TravelQuestionResponseForm
		# context['travel_question_res_res_form'] = forms.TravelQuestionResponseResponseForm

		return context

# Info, Question, Local Create View
class TravelQuestionView(CreateView):
	template_name = 'travel_agency/form_views/travel_question_form.html'
	form_class = forms.TravelQuestionForm

	def get_context_data(self, **kwargs):
		context = super(TravelQuestionView, self).get_context_data(**kwargs)
		context['country'] = self.request.GET.get('country', None)
		return context

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		# elif not request.GET.get('country', None):
		# 	return redirect('home:chooser')
		else:
			return super(TravelQuestionView, self).dispatch(request, *args, **kwargs)

	def get_success_url(self):
		# find your next url here
		next_url = self.request.POST.get('next', None) # here method should be GET or POST.
		if next_url:
			return "%s" % (next_url) # you can include some query strings as well
		else :
			# reverse('edit_project', kwargs={'project_id':4})
			country = "country=" + self.request.POST.get('country', None)
			return "%s?%s" % (reverse('home:home'), country) # what url you wish to return

	def form_valid(self, form):
		country = self.request.POST.get('country', None)
		cc = country.split("-")
		country_city = CountryCity.objects.get(country_code=int(cc[0]), city_alias=cc[1])

		travelQuestion = form.save(commit=False)
		travelQuestion.user = self.request.user
		travelQuestion.country_city = country_city
		travelQuestion.save()
		return super(TravelQuestionView, self).form_valid(form)


class TravelInfoView(CreateView):
	template_name = 'travel_agency/form_views/travel_info_form.html'
	form_class = forms.TravelInfoForm

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		# elif not request.GET.get('country', None):
		# 	return redirect('home:chooser')
		else:
			return super(TravelInfoView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(TravelInfoView, self).get_context_data(**kwargs)
		context['country'] = self.request.GET.get('country', None)
		return context

	def get_success_url(self):
		# find your next url here
		next_url = self.request.POST.get('next', None) # here method should be GET or POST.
		if next_url:
			return "%s" % (next_url) # you can include some query strings as well
		else :
			country = "country=" + self.request.POST.get('country', None)
			return "%s?%s" % (reverse('home:home'), country) # what url you wish to return

	def form_valid(self, form):
		country = self.request.POST.get('country', None)
		cc = country.split("-")
		country_city = CountryCity.objects.get(country_code=int(cc[0]), city_alias=cc[1])

		travelInfo = form.save(commit=False)
		travelInfo.user = self.request.user	
		travelInfo.country_city = country_city
		travelInfo.save()
		return super(TravelInfoView, self).form_valid(form)


class TravelLocalView(CreateView):
	template_name = 'travel_agency/form_views/travel_local_form.html'
	form_class = forms.TravelLocalForm

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('intro')
		# elif not request.GET.get('country', None):
		# 	return redirect('home:chooser')
		else:
			return super(TravelLocalView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(TravelLocalView, self).get_context_data(**kwargs)
		context['country'] = self.request.GET.get('country', None)
		return context

	def get_success_url(self):
		# find your next url here
		next_url = self.request.POST.get('next', None) # here method should be GET or POST.
		if next_url:

templates/travel_agency/travel_questions/_main_travel_question_home.html
{% load i18n %}
{% load get_item %}
{% load staticfiles %}

<script src="{% static "js/travel_q_i_functions/travel_questions_functions.js" %}"></script>
<script src="{% static "js/show_more.js" %}"></script>

<div class="modal-dialog modal-lg">
	<div class="modal-content">
		{% if travel_question %}
			{% if travel_question.user == user %}
				<script type="text/javascript">
					$(document).ready(function() {
						$('.modal-footer').remove();
					});
				</script>
			{% endif %}
			<div class="modal-header">
				<div class="row">
					<div class="col-md-12">
						<h4 class="modal-title" id="question_frame_label">{{ travel_question.title }}</h4>
					</div>
					<div class="col-md-2">
						{% if travel_question.user == user %}
						<button type='button' class="close dropdown-toggle" id="menu_edit" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span aria-hidden="true" class="fa fa-bars"></span></button>
						<ul class="dropdown-menu" aria-labelledby="menu_edit">
							<li><a href="{% url 'home:travel-question-update-form' travel_question.pk %}">Edit</a></li>
							<li><a href="#" data-toggle="modal" data-target="#del_com">Delete</a></li>
						</ul>
						<div class="modal fade" id="del_com" role="dialog" aria-labelledby="del_label">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
										<h4 class="modal-title" id="del_label">{% trans "Delete Confirmation" %}</h4>
									</div>
									<div class="modal-body">
										<button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</button>
										<button type="button" id="qus_del" data-dismiss="modal" class="btn btn-danger">{% trans "Delete" %}</button>
									</div>
								</div><!-- /.modal-content -->
							</div><!-- /.modal-dialog -->
						</div><!-- /.modal -->

						<script type="text/javascript">
						$(document).ready(function() {
							$('#qus_del').click(function() {
								$.ajax({
									url: "{% url 'api:travel-question-detail' travel_question.pk %}",
									type: 'DELETE',
									success: function(data) {
										console.log(data);
										location.reload();
									},
									error: function(e) {
										console.log(e);
										location.reload();
									}
								});
							});
						});
						</script>
						{% endif %}
					</div>
					<div class="col-md-2">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					</div>
				</div>
				<div class="row" id="question_user">
				</div>
			</div>
			<div class="modal-body">
				{{ travel_question.detail|safe }}
				<hr>
				<div class="alert alert-success">
					{% if travel_question_responses %}
						{{ travel_question_responses.count }} 
					{% else %}
						0 
					{% endif %}
					{% trans "Answered" %}
				</div>
				<div class="list-group">
					{% for travel_question_response in travel_question_responses %}
						{% include "travel_agency/travel_questions/_list_item_question_response.html" with travel_question_response=travel_question_response travel_question_res_res_s=travel_question_res_res_s|get_item:travel_question_response.pk %}

						{% if travel_question_response.user == user %}
							<script type="text/javascript">
								$(document).ready(function() {
									$('.modal-footer').remove();

									// Do edit or save
									$('#question_res_self').click(function() {
										editOrSaveRes(
											'{% trans "Edit" %}',
											'{% trans "Save" %}',
											'{% trans "Response..." %}',
											{{ travel_question_response.pk }},
											"{% url 'api:travel-question-response-detail' travel_question_response.pk %}",
											{{ travel_question.pk }},
											{{ user.pk }});
									});
								});
							</script>
						{% endif %}
					{% endfor %}
				</div>
			</div>
			<div class="modal-footer">
				<!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
				<div class="row">
					<div class="col-md-16">
						<h4 class="pull-left">{% trans "Send Your Answer" %}</h4>
					</div>
				</div>
				<!-- <div class="row" style="text-align: center">
					<div class="col-md-4">{% trans "Local Help" %}</div>
					<div class="col-md-8">
						<input id="is_question_connected" class="form-control" type="checkbox" name="is-c-checkbox" checked>
					</div>
				</div> -->
				<div class="row">
					<div class="btn col-md-16">
						<textarea id="travel_question_response_textarea" class="form-control" rows="3" placeholder="{% trans 'Response...' %}"></textarea>
					</div>
				</div>
				<button type="button" id="send_travel_question_response_btn" class="btn btn-primary form-control" data-dismiss="modal">Send</button>
			</div>
		{% endif %}
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	loadAllImage(function(msg, data) {
		console.log(msg, data);
	});

	// $("[name='is-c-checkbox']").bootstrapSwitch('state', false);
	// $("[name='is-c-checkbox']").bootstrapSwitch('onText', 'YES');
	// $("[name='is-c-checkbox']").bootstrapSwitch('offText', 'NO');

	$('#send_travel_question_response_btn').click(function(){
		sendQuestionResponse(
		"{% url 'api:travel-question-response-list' %}",
		{{ travel_question.pk }},
		{{ user.pk }});
	});
});
</script>

templates/travel_agency/travel_questions/_travel_question_frame.html
<!-- Travel Info Modal -->
<div class="modal fade" id="travel_question_frame" tabindex="-1" role="dialog" aria-labelledby="question_frame_label" aria-hidden="true">

</div>